{
  "openapi": "3.0.1",
  "info": {
    "title": "Default module",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "user id"
    }
  ],
  "paths": {
    "/oauth2/authorization/kakao": {
      "get": {
        "summary": "로그인",
        "deprecated": false,
        "description": "카카오 OAuth 로그인 이후 워켓 자체 JWT 발급 ( 쿠키에 access token, refresh token 저장 )\n\n검수자 : 영은, 경남",
        "tags": [],
        "parameters": [
          {
            "name": "state",
            "in": "query",
            "description": "FREERANCER OR CLIENT",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/logout": {
      "post": {
        "summary": "로그아웃",
        "deprecated": false,
        "description": "유저를 워켓에서 로그아웃 시킵니다. ( 토큰 폐기 )\n\n검수자 : 영은, 경남",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/token/refresh": {
      "post": {
        "summary": "카카오 토큰 재발급",
        "deprecated": false,
        "description": "카카오 access token을 재발급합니다. ( 워켓 access token은 만료 되기 전 자동 갱신 )\n\n검수자 : 영은, 경남",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/unlink": {
      "post": {
        "summary": "회원 탈퇴",
        "deprecated": false,
        "description": "워켓의 회원을 탈퇴합니다. ( 카카오 연동 해제 )\n\n검수자 : 영은, 경남",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/passcode/register": {
      "post": {
        "summary": "간편 비밀번호 등록",
        "deprecated": false,
        "description": "PIN 번호 등록 ( 프론트에서 해시값으로 전송 )\n\n검수자 : 영은, 수연",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "pin": {
                    "type": "string",
                    "description": "비밀번호(해시값)"
                  }
                },
                "required": [
                  "pin"
                ]
              },
              "example": {
                "pin": "123456"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/auth/passcode/verify": {
      "post": {
        "summary": "간편 비밀번호 검증",
        "deprecated": false,
        "description": "등록된 PIN 검증 ( 2차 인증 )\n\n검수자 : 영은, 수연",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "passcode": {
                    "type": "string",
                    "description": "비밀번호 해시값"
                  }
                },
                "required": [
                  "passcode"
                ]
              },
              "example": {
                "passcode": "123456"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}": {
      "post": {
        "summary": "유저 정보 수정",
        "deprecated": false,
        "description": "프리랜서 프로필 정보를 변경합니다.\n\n검수자 : 영은, 경남",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "userId",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "birthDate": {
                    "type": "string",
                    "format": "date",
                    "description": "생일",
                    "nullable": true
                  },
                  "gender": {
                    "type": "string",
                    "enum": [
                      "MALE",
                      "FEMALE"
                    ],
                    "description": "성별",
                    "nullable": true
                  },
                  "businessSector": {
                    "type": "string",
                    "maxLength": 100,
                    "description": "업종",
                    "nullable": true
                  },
                  "businessSectorYears": {
                    "type": "integer",
                    "minimum": -9223372036854776000,
                    "maximum": 9223372036854776000,
                    "description": "업력",
                    "nullable": true
                  },
                  "businessRegistrationNumber": {
                    "type": "string",
                    "description": "사업자등록번호"
                  }
                },
                "required": [
                  "businessRegistrationNumber"
                ]
              },
              "example": {
                "birthDate": "1987-08-05",
                "gender": "MALE",
                "businessSector": "청소",
                "businessSectorYears": 4,
                "businessRegistrationNumber": "69077934708"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "summary": "유저 정보 조회",
        "deprecated": false,
        "description": "프리랜서의 정보를 조회합니다. ( 마이페이지 조회용 )\n\n검수자 : 영은, 경남",
        "operationId": "userId",
        "tags": [
          "user id"
        ],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "userId",
            "in": "path",
            "description": "유저 PK",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "maxLength": 50,
                      "description": "이름"
                    },
                    "role": {
                      "type": "string",
                      "enum": [
                        "FREELANCER",
                        "CLIENT",
                        "ADMIN"
                      ],
                      "default": "FREELANCER",
                      "description": "유저 role\n",
                      "nullable": true
                    },
                    "phone": {
                      "type": "string",
                      "maxLength": 20,
                      "description": "핸드폰번호 11자리",
                      "nullable": true
                    },
                    "birthDate": {
                      "type": "string",
                      "format": "date",
                      "description": "생년월일",
                      "nullable": true
                    },
                    "gender": {
                      "type": "string",
                      "enum": [
                        "MALE",
                        "FEMALE"
                      ],
                      "description": "성별",
                      "nullable": true
                    },
                    "businessSector": {
                      "type": "string",
                      "maxLength": 100,
                      "description": "업종",
                      "nullable": true
                    },
                    "businessSectorYears": {
                      "type": "integer",
                      "minimum": -9223372036854776000,
                      "maximum": 9223372036854776000,
                      "description": "업력",
                      "nullable": true
                    },
                    "businessRegistrationNumber": {
                      "type": "string",
                      "maxLength": 20,
                      "description": "사업자등록번호\n",
                      "nullable": true
                    }
                  },
                  "required": [
                    "name"
                  ]
                },
                "example": {
                  "name": "이영은",
                  "role": "FREELANCER",
                  "phone": "01023970938",
                  "birthDate": "1998-11-23",
                  "gender": "FEMALE",
                  "businessSector": "디자인",
                  "businessSectorYears": 8,
                  "businessRegistrationNumber": "9325863715"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/contracts/extract": {
      "post": {
        "summary": "계약서 추출",
        "deprecated": false,
        "description": "계약서 메타 데이터 추출 ( OCR + LLM )\nOCR로 JSON 데이터 추출 -> Gemini 로 매핑 결과 추출\n\n검수자 : 영은, 윤미",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "format": "binary",
                    "type": "string",
                    "description": "pdf,png,jpg 파일\n",
                    "example": ""
                  }
                }
              },
              "examples": {}
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "contractInfo": {
                      "type": "object",
                      "properties": {
                        "title": {
                          "type": "string"
                        },
                        "amount": {
                          "type": "string"
                        },
                        "startDate": {
                          "type": "string",
                          "format": "date"
                        },
                        "endDate": {
                          "type": "string",
                          "format": "date"
                        }
                      },
                      "required": [
                        "title",
                        "startDate",
                        "amount",
                        "endDate"
                      ]
                    },
                    "clientInfo": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "phone": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "phone"
                      ]
                    },
                    "freelancerInfo": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "phone": {
                          "type": "string"
                        },
                        "account": {
                          "type": "string"
                        },
                        "bank": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "phone",
                        "account",
                        "bank"
                      ]
                    }
                  },
                  "required": [
                    "contractInfo",
                    "clientInfo",
                    "freelancerInfo"
                  ]
                },
                "example": {
                  "contractInfo": {
                    "title": "ㅇㅇ 프로젝트",
                    "amount": "150000",
                    "startDate": "2026-03-08",
                    "endDate": "2025-07-24"
                  },
                  "clientInfo": {
                    "name": "김윤미",
                    "phone": "010-1234-5678"
                  },
                  "freelancerInfo": {
                    "name": "이영은",
                    "phone": "010-8765-4321",
                    "account": "123515651",
                    "bank": "국민은행"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/contracts": {
      "post": {
        "summary": "계약서 등록",
        "deprecated": false,
        "description": "계약서 신규 등록 ( PDF 업로드 포함 )\n\n검수자 : 영은, 윤서, 윤미",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "계약서 업로드인지, 계약서 생성 건인지",
                    "enum": [
                      "CREATED",
                      "UPLOAD"
                    ]
                  },
                  "contractInfo": {
                    "type": "object",
                    "properties": {
                      "title": {
                        "type": "string"
                      },
                      "amount": {
                        "type": "number"
                      },
                      "startDate": {
                        "type": "string",
                        "format": "date"
                      },
                      "endDate": {
                        "type": "string",
                        "format": "date"
                      }
                    },
                    "required": [
                      "title",
                      "startDate",
                      "amount",
                      "endDate"
                    ]
                  },
                  "clientInfo": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "name",
                      "phone"
                    ]
                  },
                  "freelancerInfo": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "type": "string"
                      },
                      "phone": {
                        "type": "string"
                      },
                      "account": {
                        "type": "string"
                      },
                      "bank": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "name",
                      "phone",
                      "account",
                      "bank"
                    ]
                  }
                },
                "required": [
                  "type",
                  "contractInfo",
                  "clientInfo",
                  "freelancerInfo"
                ]
              },
              "example": {
                "type": "UPDATE",
                "contractInfo": {
                  "title": "ㅇㅇ 프로젝트",
                  "amount": 150000,
                  "startDate": "2025-12-05",
                  "endDate": "2025-03-13"
                },
                "clientInfo": {
                  "name": "이영은",
                  "phone": "010-2815-1244"
                },
                "freelancerInfo": {
                  "name": "김윤서",
                  "phone": "010-3923-4054",
                  "account": "135165135845",
                  "bank": "국민은행"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "transactionId": {
                      "type": "integer",
                      "description": "거래 id"
                    }
                  },
                  "required": [
                    "transactionId"
                  ]
                },
                "example": {
                  "transactionId": 14
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/contracts/{contractId}/signatures": {
      "post": {
        "summary": "서명 등록",
        "deprecated": false,
        "description": "프리랜서/의뢰인 서명 저장\n\n검수자 : 영은, 수연, 윤서",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "contractId",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "signatureUrl": {
                    "type": "string",
                    "description": "클라이언트 서명 url"
                  }
                },
                "required": [
                  "signatureUrl"
                ]
              },
              "example": {
                "signatureUrl": "https://gifted-colon.org/"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "nullable": true
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/transactions/{transactionId}/preview": {
      "get": {
        "summary": "거래 정보 미리보기 ",
        "deprecated": false,
        "description": "거래 프리뷰 정보 ( 프리랜서 이름, 의뢰인 이름, 계약명 )을 반환합니다.\n비고 : 토큰 없이도 접근 가능한 API \n",
        "tags": [],
        "parameters": [
          {
            "name": "transactionId",
            "in": "path",
            "description": "거래 PK",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "freelancerName": {
                      "type": "string",
                      "description": "프리랜서이름"
                    },
                    "clientName": {
                      "type": "string",
                      "description": "의뢰인이름"
                    },
                    "title": {
                      "type": "string",
                      "description": "계약명"
                    }
                  },
                  "required": [
                    "freelancerName",
                    "clientName",
                    "title"
                  ]
                },
                "example": {
                  "freelancerName": "이영은",
                  "clientName": "신수연",
                  "title": "ㅇㅇ 프로젝트"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/transactions/{transactionId}/permissions": {
      "get": {
        "summary": "거래 접근권한 판단",
        "deprecated": false,
        "description": "거래 당사자인 의뢰인이 맞는지 판별하여 접근권한을 반환합니다.\n\n참고 ( 백엔드 로직 ) : \n거래 의뢰인 매핑 상태에 따른 분기\n1. 거래에 매핑된 의뢰인 존재 x\n- API를 호출한 주체(의뢰인 유저)와 프리랜서가 작성한 계약서 상 도급인 정보가 동일하면 의뢰인으로 매핑 후 접근 권한 true 반환\n- 동일하지 않으면 -> 접근 권한 false 반환\n2. 거래에 매핑된 의뢰인 존재 ㅇ\n- api 호출 주체 유저가 실제 매핑된 의뢰인과 동일한지 판별\n- 동일하면 -> 접근 권한 true 반환\n- 동일하지 않으면 -> 접근 권한 false 반환",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "transactionId",
            "in": "path",
            "description": "거래 PK",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "userRole": {
                      "type": "string",
                      "enum": [
                        "CLIENT",
                        "FREELANCER"
                      ]
                    },
                    "permission": {
                      "type": "boolean",
                      "nullable": true
                    }
                  },
                  "required": [
                    "permission",
                    "userRole"
                  ]
                },
                "example": {
                  "userRole": "CLIENT",
                  "permission": null
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/transactions": {
      "get": {
        "summary": "거래 전체 조회",
        "deprecated": false,
        "description": "프리랜서의 월별 전체 거래 목록 조회\n\n검수자 : 영은, 기연",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "year",
            "in": "query",
            "description": "",
            "required": false,
            "example": "2025",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "month",
            "in": "query",
            "description": "",
            "required": false,
            "example": "11",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "freelancerName": {
                      "type": "string",
                      "description": "프리랜서 이름"
                    },
                    "totalAmount": {
                      "type": "string",
                      "description": "이번달 소득액"
                    },
                    "statusCounts": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "status": {
                            "type": "string",
                            "description": "상태"
                          },
                          "count": {
                            "type": "integer",
                            "description": "건수"
                          }
                        },
                        "required": [
                          "status",
                          "count"
                        ]
                      },
                      "description": "상태별 건수"
                    },
                    "contractList": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "transactionId": {
                            "type": "number",
                            "description": "거래 PK"
                          },
                          "title": {
                            "type": "string",
                            "description": "거래명"
                          },
                          "status": {
                            "type": "string",
                            "description": "거래 상태"
                          },
                          "amount": {
                            "type": "number",
                            "description": "거래금액"
                          },
                          "startDate": {
                            "type": "string",
                            "description": "계약 시작일"
                          },
                          "endDate": {
                            "type": "string",
                            "description": "계약 종료일"
                          }
                        },
                        "required": [
                          "status",
                          "amount",
                          "startDate",
                          "title",
                          "endDate",
                          "transactionId"
                        ]
                      },
                      "description": "거래 내역"
                    }
                  },
                  "required": [
                    "freelancerName",
                    "totalAmount",
                    "statusCounts",
                    "contractList"
                  ]
                },
                "example": "{\r\n    \"freelancerName\": \"Teresa Donnelly\",\r\n    \"totalAmount\": \"526.49\",\r\n    \"statusCounts\": [\r\n        {\r\n            \"status\": \"CREATED\",\r\n            \"count\": 7\r\n        },\r\n        {\r\n            \"status\": \"SIGNED\",\r\n            \"count\": 13\r\n        },\r\n        {\r\n            \"status\": \"DEPOSIT_HOLD\",\r\n            \"count\": 5\r\n        },\r\n        {\r\n            \"status\": \"PAYMENT_CONFIRMED\",\r\n            \"count\": 0\r\n        }\r\n         {\r\n            \"status\": \"SETTLED\",\r\n            \"count\": 15\r\n        },\r\n    ],\r\n    \"contractList\": [\r\n        {\r\n            \"transactionId\": 57851,\r\n            \"title\": \"ㅇㅇ 프로젝트\",\r\n            \"status\": \"DEPOSIT_HOLD\",\r\n            \"amount\": 150000,\r\n            \"startDate\": \"2025-01-29\",\r\n            \"endDate\": \"2024-12-24\"\r\n        },\r\n        {\r\n            \"transactionId\": 57852,\r\n            \"title\": \"ㅇㅇ 프로젝트\",\r\n            \"status\": \"SETTLED\",\r\n            \"amount\": 150000,\r\n            \"startDate\": \"2025-01-29\",\r\n            \"endDate\": \"2024-12-24\"\r\n        },\r\n        {\r\n            \"transactionId\": 57853,\r\n            \"title\": \"ㅇㅇ 프로젝트\",\r\n            \"status\": \"SIGNED\",\r\n            \"amount\": 150000,\r\n            \"startDate\": \"2025-01-29\",\r\n            \"endDate\": \"2024-12-24\"\r\n        }\r\n    ]\r\n}"
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/transactions/{transactionId}": {
      "get": {
        "summary": "거래 상세 조회",
        "deprecated": false,
        "description": "프리랜서의 특정 거래 상세 조회\n\n검수자 : 영은, 수연, 기연",
        "tags": [],
        "parameters": [
          {
            "name": "accesSToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "transactionId",
            "in": "path",
            "description": "",
            "required": true,
            "schema": {
              "type": "integer"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "description": "거래 상태",
                      "enum": [
                        "CREATED",
                        "SIGNED",
                        "DEPOSIT_HOLD",
                        "PAYMENT_CONFIRMED",
                        "SETTLED"
                      ],
                      "default": "CREATED"
                    },
                    "signedAt": {
                      "type": "string",
                      "format": "date-time",
                      "default": null,
                      "description": "SIGNED 시점",
                      "nullable": true
                    },
                    "depositHoldAt": {
                      "type": "string",
                      "format": "date-time",
                      "default": null,
                      "description": "DIPOSIT_HOLD 시점",
                      "nullable": true
                    },
                    "paymentConfirmedAt": {
                      "type": "string",
                      "format": "date-time",
                      "default": null,
                      "description": "PAYMENT_CONFIRMED 시점",
                      "nullable": true
                    },
                    "settledAt": {
                      "type": "string",
                      "format": "date-time",
                      "default": null,
                      "description": "SETTLED 시점",
                      "nullable": true
                    },
                    "createdAt": {
                      "type": "string",
                      "format": "date-time",
                      "default": "CURRENT_TIMESTAMP",
                      "description": "CREATED 시점",
                      "nullable": true
                    },
                    "contractId": {
                      "type": "number"
                    },
                    "settledAmount": {
                      "type": "number",
                      "description": "정산 금액\n"
                    },
                    "contractFileUrl": {
                      "type": "string",
                      "description": "계약서 원본 S3 URL"
                    },
                    "contractInfo": {
                      "type": "object",
                      "properties": {
                        "title": {
                          "type": "string"
                        },
                        "amount": {
                          "type": "number"
                        },
                        "startDate": {
                          "type": "string",
                          "format": "date"
                        },
                        "endDate": {
                          "type": "string",
                          "format": "date"
                        }
                      },
                      "required": [
                        "title",
                        "startDate",
                        "amount",
                        "endDate"
                      ]
                    },
                    "clientInfo": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "phone": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "phone"
                      ]
                    },
                    "freelancerInfo": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "phone": {
                          "type": "string"
                        },
                        "account": {
                          "type": "string"
                        },
                        "bank": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "phone",
                        "account",
                        "bank"
                      ]
                    }
                  },
                  "required": [
                    "contractId",
                    "settledAmount",
                    "contractInfo",
                    "clientInfo",
                    "freelancerInfo"
                  ]
                },
                "example": {
                  "status": "SIGNED",
                  "signedAt": "2025-11-11T20:00:42.074Z",
                  "depositHoldAt": "2025-11-11T16:08:55.215Z",
                  "paymentConfirmedAt": "2025-11-11T16:49:24.553Z",
                  "settledAt": "2025-11-12T02:40:58.476Z",
                  "createdAt": "2025-11-12T07:06:05.705Z",
                  "contractId": 956,
                  "settledAmount": 715.89,
                  "contractFileUrl": "https://loremflickr.com/167/2526?lock=3238486552340916",
                  "contractInfo": {
                    "title": "through during yahoo any only as worth ironclad beard filthy",
                    "amount": 262.19,
                    "startDate": "2025-04-02",
                    "endDate": "2026-05-17"
                  },
                  "clientInfo": {
                    "name": "Lillie Rempel",
                    "phone": "(519) 910-4266"
                  },
                  "freelancerInfo": {
                    "name": "Lydia Koss Sr.",
                    "phone": "(856) 288-3656",
                    "account": "exercitation in",
                    "bank": "esse aliqua"
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/statistics": {
      "get": {
        "summary": "통계 조회",
        "deprecated": false,
        "description": "소득관리 탭 통계 조회 ( 소득액 기반, 거래수 기반 )\n\n검수자 : 영은, 윤서",
        "tags": [],
        "parameters": [
          {
            "name": "accessToken",
            "in": "cookie",
            "description": "",
            "required": false,
            "example": "<JWT_ACCESS_TOKEN>",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "currentYearProfit": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "incomes": {
                            "type": "number",
                            "description": "이번년도 수익\n"
                          },
                          "transactions": {
                            "type": "number",
                            "description": "이번년도 거래수\n"
                          }
                        },
                        "required": [
                          "incomes",
                          "transactions"
                        ]
                      },
                      "description": "이번년도 통계\n"
                    },
                    "statistics": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "month": {
                            "type": "string",
                            "description": "달"
                          },
                          "incomes": {
                            "type": "number",
                            "description": "소득액\n"
                          },
                          "transactions": {
                            "type": "number",
                            "description": "거래수"
                          }
                        },
                        "required": [
                          "transactions",
                          "incomes",
                          "month"
                        ]
                      },
                      "description": "최근 3개월 통계"
                    }
                  },
                  "required": [
                    "currentYearProfit",
                    "statistics"
                  ]
                },
                "example": {
                  "currentYearProfit": [
                    {
                      "incomes": 6850000,
                      "transactions": 95
                    }
                  ],
                  "statistics": [
                    {
                      "month": "2025-09",
                      "incomes": 350000,
                      "transactions": 3
                    },
                    {
                      "month": "2025-10",
                      "incomes": 260000,
                      "transactions": 2
                    },
                    {
                      "month": "2025-11",
                      "incomes": 640000,
                      "transactions": 8
                    }
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}